config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  resources :tipo_pokemons

  resources :tipos

  resources :pokedexes

  resources :pokemons

  resources :treinadors

  resources :users	
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  root 'sessions#new'

end

app/models/pokedex.rb
class Pokedex < ActiveRecord::Base
  belongs_to :pokemon
  validates_uniqueness_of :pokemon_id
end

app/controllers/pokedexes_controller.rb
class PokedexesController < ApplicationController
  before_action :set_pokedex, only: [:show, :edit, :update, :destroy]

  # GET /pokedexes
  # GET /pokedexes.json
  def index
    @pokedexes = Pokedex.all
  end

  # GET /pokedexes/1
  # GET /pokedexes/1.json
  def show
  end

  # GET /pokedexes/new
  def new
    @pokedex = Pokedex.new
  end

  # GET /pokedexes/1/edit
  def edit
  end

  # POST /pokedexes
  # POST /pokedexes.json
  def create
    @pokedex = Pokedex.new(pokedex_params)

    respond_to do |format|
      if @pokedex.save
        format.html { redirect_to @pokedex, notice: 'Pokedex was successfully created.' }
        format.json { render :show, status: :created, location: @pokedex }
      else
        format.html { render :new }
        format.json { render json: @pokedex.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokedexes/1
  # PATCH/PUT /pokedexes/1.json
  def update
    respond_to do |format|
      if @pokedex.update(pokedex_params)
        format.html { redirect_to @pokedex, notice: 'Pokedex was successfully updated.' }
        format.json { render :show, status: :ok, location: @pokedex }
      else
        format.html { render :edit }
        format.json { render json: @pokedex.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokedexes/1
  # DELETE /pokedexes/1.json
  def destroy
    @pokedex.destroy
    respond_to do |format|
      format.html { redirect_to pokedexes_url, notice: 'Pokedex was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokedex
      @pokedex = Pokedex.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pokedex_params
      params.require(:pokedex).permit(:numero, :pokemon_id)
    end
end

app/helpers/pokedexes_helper.rb
module PokedexesHelper
end

app/views/pokedexes/_form.html.erb
<%= form_for(@pokedex) do |f| %>
  <% if @pokedex.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pokedex.errors.count, "error") %> prohibited this pokedex from being saved:</h2>

      <ul>
      <% @pokedex.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :numero %><br>
    <%= f.number_field :numero %>
  </div>
  <div class="field">
    <%= f.label :pokemon_id %><br>
    <%= f.text_field :pokemon_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pokedexes/edit.html.erb
<h1>Editing pokedex</h1>

<%= render 'form' %>

<%= link_to 'Show', @pokedex %> |
<%= link_to 'Back', pokedexes_path %>

app/views/pokedexes/index.html.erb
<section id="view">

<h1>Listing pokedexes</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Numero</th>
      <th>Pokemon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pokedexes.each do |pokedex| %>
      <tr>
        <td><%= pokedex.id %></td>
        <td><%= pokedex.numero %></td>
        <td><%= Pokemon.find(pokedex.pokemon).nome %></td>
        <td><%= link_to 'Show', pokedex %></td>
	<% if current_user.role == "admin" %>
	        <td><%= link_to 'Edit', edit_pokedex_path(pokedex) %></td>
       		<td><%= link_to 'Destroy', pokedex, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.role == "admin" %>
	<%= link_to 'New Pokedex', new_pokedex_path %>
<% end %>
</section>

app/views/pokedexes/new.html.erb
<h1>New pokedex</h1>

<%= render 'form' %>

<%= link_to 'Back', pokedexes_path %>

app/views/pokedexes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @pokedex.id %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @pokedex.numero %>
</p>

<p>
  <strong>Pokemon:</strong>
  <%= Pokemon.find(@pokedex.pokemon_id).nome %>
</p>

<% if current_user.role == "admin" %>
	<%= link_to 'Edit', edit_pokedex_path(@pokedex) %> |
<% end %>
<%= link_to 'Back', pokedexes_path %>