config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  resources :tipo_pokemons

  resources :tipos

  resources :pokedexes

  resources :pokemons

  resources :treinadors

  resources :users	
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  root 'sessions#new'

end

app/models/tipo_pokemon.rb
class TipoPokemon < ActiveRecord::Base
  self.table_name = "pokemons_tipos"
  belongs_to :tipo
  belongs_to :pokemon
end

app/controllers/tipo_pokemons_controller.rb
class TipoPokemonsController < ApplicationController
  before_action :set_tipo_pokemon, only: [:show, :edit, :update, :destroy]

  # GET /tipo_pokemons
  # GET /tipo_pokemons.json
  def index
    @tipo_pokemons = TipoPokemon.all
  end

  # GET /tipo_pokemons/1
  # GET /tipo_pokemons/1.json
  def show
  end

  # GET /tipo_pokemons/new
  def new
    @tipo_pokemon = TipoPokemon.new
  end

  # GET /tipo_pokemons/1/edit
  def edit
  end

  # POST /tipo_pokemons
  # POST /tipo_pokemons.json
  def create
    @tipo_pokemon = TipoPokemon.new(tipo_pokemon_params)

    respond_to do |format|
      if @tipo_pokemon.save
        format.html { redirect_to @tipo_pokemon, notice: 'Tipo pokemon was successfully created.' }
        format.json { render :show, status: :created, location: @tipo_pokemon }
      else
        format.html { render :new }
        format.json { render json: @tipo_pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_pokemons/1
  # PATCH/PUT /tipo_pokemons/1.json
  def update
    respond_to do |format|
      if @tipo_pokemon.update(tipo_pokemon_params)
        format.html { redirect_to @tipo_pokemon, notice: 'Tipo pokemon was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo_pokemon }
      else
        format.html { render :edit }
        format.json { render json: @tipo_pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_pokemons/1
  # DELETE /tipo_pokemons/1.json
  def destroy
    @tipo_pokemon.destroy
    respond_to do |format|
      format.html { redirect_to tipo_pokemons_url, notice: 'Tipo pokemon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_pokemon
      @tipo_pokemon = TipoPokemon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_pokemon_params
      params.require(:tipo_pokemon).permit(:tipo_id, :pokemon_id)
    end
end

app/helpers/tipo_pokemons_helper.rb
module TipoPokemonsHelper
end

app/views/tipo_pokemons/_form.html.erb
<%= form_for(@tipo_pokemon) do |f| %>
  <% if @tipo_pokemon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tipo_pokemon.errors.count, "error") %> prohibited this tipo_pokemon from being saved:</h2>

      <ul>
      <% @tipo_pokemon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo_id %><br>
    <%= f.text_field :tipo_id %>
  </div>
  <div class="field">
    <%= f.label :pokemon_id %><br>
    <%= f.text_field :pokemon_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tipo_pokemons/edit.html.erb
<h1>Editing tipo_pokemon</h1>

<%= render 'form' %>

<%= link_to 'Show', @tipo_pokemon %> |
<%= link_to 'Back', tipo_pokemons_path %>

app/views/tipo_pokemons/index.html.erb
<h1>Listing tipo_pokemons</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Pokemon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipo_pokemons.each do |tipo_pokemon| %>
      <tr>
        <td><%= Tipo.find(tipo_pokemon.tipo_id).nome %></td>
        <td><%= Pokemon.find(tipo_pokemon.pokemon_id).nome %></td>
        <td><%= link_to 'Show', tipo_pokemon %></td>
	<% if current_user.role == "admin" %>
        	<td><%= link_to 'Edit', edit_tipo_pokemon_path(tipo_pokemon) %></td>
        	<td><%= link_to 'Destroy', tipo_pokemon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.role == "admin" %>
	<%= link_to 'New Tipo pokemon', new_tipo_pokemon_path %>
<% end %>

app/views/tipo_pokemons/new.html.erb
<h1>New tipo_pokemon</h1>

<%= render 'form' %>

<%= link_to 'Back', tipo_pokemons_path %>

app/views/tipo_pokemons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= Tipo.find(@tipo_pokemon.tipo_id).nome %>
</p>

<p>
  <strong>Pokemon:</strong>
  <%= Pokemon.find(@tipo_pokemon.pokemon_id).nome %>
</p>

<% if current_user.role == "admin" %>
	<%= link_to 'Edit', edit_tipo_pokemon_path(@tipo_pokemon) %> |
<% end %>
<%= link_to 'Back', tipo_pokemons_path %>