config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  resources :tipo_pokemons

  resources :tipos

  resources :pokedexes

  resources :pokemons

  resources :treinadors

  resources :users	
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  root 'sessions#new'

end

app/models/pokemon.rb
class Pokemon < ActiveRecord::Base
  belongs_to :treinador
  has_and_belongs_to_many :tipos, :dependent => :destroy
  has_one :pokedex, :dependent => :destroy
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: [:show, :edit, :update, :destroy]

  # GET /pokemons
  # GET /pokemons.json
  def index
    @pokemons = Pokemon.all
  end

  # GET /pokemons/1
  # GET /pokemons/1.json
  def show
  end

  # GET /pokemons/new
  def new
    @pokemon = Pokemon.new
  end

  # GET /pokemons/1/edit
  def edit
  end

  # POST /pokemons
  # POST /pokemons.json
  def create
    @pokemon = Pokemon.new(pokemon_params)

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully created.' }
        format.json { render :show, status: :created, location: @pokemon }
      else
        format.html { render :new }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemons/1
  # PATCH/PUT /pokemons/1.json
  def update
    respond_to do |format|
      if @pokemon.update(pokemon_params)
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully updated.' }
        format.json { render :show, status: :ok, location: @pokemon }
      else
        format.html { render :edit }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemons/1
  # DELETE /pokemons/1.json
  def destroy
    @pokemon.destroy
    respond_to do |format|
      format.html { redirect_to pokemons_url, notice: 'Pokemon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pokemon_params
      params.require(:pokemon).permit(:nome, :cp, :hp, :treinador_id)
    end
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/pokemons/_form.html.erb
<%= form_for(@pokemon) do |f| %>
  <% if @pokemon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pokemon.errors.count, "error") %> prohibited this pokemon from being saved:</h2>

      <ul>
      <% @pokemon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :cp %><br>
    <%= f.number_field :cp %>
  </div>
  <div class="field">
    <%= f.label :hp %><br>
    <%= f.number_field :hp %>
  </div>
  <div class="field">
    <%= f.label :treinador_id %><br>
    <%= f.text_field :treinador_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pokemons/edit.html.erb
<h1>Editing pokemon</h1>

<%= render 'form' %>

<%= link_to 'Show', @pokemon %> |
<%= link_to 'Back', pokemons_path %>

app/views/pokemons/index.html.erb
<h1>Listing pokemons</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Nome</th>
      <th>Cp</th>
      <th>Hp</th>
      <th>Treinador</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pokemons.each do |pokemon| %>
      <tr>
        <td><%= pokemon.id %></td>
        <td><%= pokemon.nome %></td>
        <td><%= pokemon.cp %></td>
        <td><%= pokemon.hp %></td>
        <td><%= Treinador.find(pokemon.treinador_id).nome %></td>
        <td><%= link_to 'Show', pokemon %></td>
	<% if current_user.role == "admin" %>
	        <td><%= link_to 'Edit', edit_pokemon_path(pokemon) %></td>
       		<td><%= link_to 'Destroy', pokemon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.role == "admin" %>
 <%= link_to 'New Pokemon', new_pokemon_path %>
	<% end %>

app/views/pokemons/new.html.erb
<h1>New pokemon</h1>

<%= render 'form' %>

<%= link_to 'Back', pokemons_path %>

app/views/pokemons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @pokemon.id %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @pokemon.nome %>
</p>

<p>
  <strong>Cp:</strong>
  <%= @pokemon.cp %>
</p>

<p>
  <strong>Hp:</strong>
  <%= @pokemon.hp %>
</p>

<p>
  <strong>Treinador:</strong>
  <%= Treinador.find(@pokemon.treinador_id).nome %>
</p>

<% if current_user.role == "admin" %>
	<%= link_to 'Edit', edit_pokemon_path(@pokemon) %> |
<% end %>
<%= link_to 'Back', pokemons_path %>